-- 20260625000000_init.sql

-- Bảng 1: challenge_results
CREATE TABLE challenge_results (
    id bigint generated by default as identity primary key,
    submission_no bigint unique not null,
    player_code text unique not null,
    full_name text not null,
    pullups integer not null,
    tier_id bigint NULL,
    tier_name text not null,
    rewards jsonb not null default '[]',
    rank_at_submission integer not null,
    idempotency_key uuid unique NULL,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    updated_by uuid NULL,
    admin_note text NULL,
    deleted_at timestamptz NULL,
    deleted_by uuid NULL
);

-- Bảng 2: achievement_tiers
CREATE TABLE achievement_tiers (
    id bigint generated by default as identity primary key,
    min_pullups integer not null,
    max_pullups integer NULL,
    title text not null,
    slug text unique not null,
    rewards jsonb not null,
    display_order integer not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Bảng 3: campaign_counters
CREATE TABLE campaign_counters (
    key text primary key,
    last_value bigint not null default 0,
    updated_at timestamptz not null default now()
);

-- Initialize counter
INSERT INTO campaign_counters (key, last_value) VALUES ('submission_no', 0);

-- Bảng 4: profiles
CREATE TABLE profiles (
    id uuid primary key references auth.users(id),
    full_name text,
    role text not null check (role in ('admin', 'staff')),
    created_at timestamptz not null default now()
);

-- Bảng 5: admin_audit_logs
CREATE TABLE admin_audit_logs (
    id bigint generated by default as identity primary key,
    admin_id uuid,
    action text not null,
    result_id bigint NULL,
    before_data jsonb NULL,
    after_data jsonb NULL,
    created_at timestamptz not null default now()
);

-- Bảng 6: leaderboard_top10
CREATE TABLE leaderboard_top10 (
    position integer primary key,
    result_id bigint unique,
    player_code text,
    display_name text,
    pullups integer,
    tier_name text,
    created_at timestamptz,
    updated_at timestamptz not null default now()
);

-- Bảng 7: leaderboard_sync
CREATE TABLE leaderboard_sync (
    id integer primary key default 1,
    version bigint not null default 0,
    updated_at timestamptz not null default now()
);

INSERT INTO leaderboard_sync (id, version) VALUES (1, 0);

-- Enable RLS
ALTER TABLE challenge_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE achievement_tiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_counters ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaderboard_top10 ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaderboard_sync ENABLE ROW LEVEL SECURITY;

-- Policies for public access (Read only to leaderboard)
CREATE POLICY "Public can read leaderboard_top10" ON leaderboard_top10 FOR SELECT USING (true);
CREATE POLICY "Public can read leaderboard_sync" ON leaderboard_sync FOR SELECT USING (true);

-- Functions
CREATE OR REPLACE FUNCTION mask_full_name(name text) RETURNS text AS $$
DECLARE
    parts text[];
    i int;
    masked_name text := '';
BEGIN
    parts := string_to_array(trim(name), ' ');
    IF array_length(parts, 1) = 1 THEN
        RETURN parts[1];
    END IF;
    
    FOR i IN 1..array_length(parts, 1) LOOP
        IF i = 1 THEN
            masked_name := parts[i];
        ELSEIF i = array_length(parts, 1) THEN
            masked_name := masked_name || ' ' || parts[i];
        ELSE
            masked_name := masked_name || ' ' || left(parts[i], 1) || '.';
        END IF;
    END LOOP;
    RETURN masked_name;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION refresh_leaderboard_top10() RETURNS void AS $$
BEGIN
    DELETE FROM leaderboard_top10 WHERE true;
    
    INSERT INTO leaderboard_top10 (position, result_id, player_code, display_name, pullups, tier_name, created_at)
    SELECT 
        row_number() over (order by pullups desc, created_at asc, id asc) as position,
        id as result_id,
        player_code,
        mask_full_name(full_name) as display_name,
        pullups,
        tier_name,
        created_at
    FROM challenge_results
    WHERE is_active = true AND deleted_at IS NULL
    ORDER BY pullups DESC, created_at ASC, id ASC
    LIMIT 10;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION submit_challenge_result(
    p_full_name text,
    p_pullups integer,
    p_idempotency_key uuid
) RETURNS jsonb AS $$
DECLARE
    v_tier achievement_tiers%ROWTYPE;
    v_submission_no bigint;
    v_player_code text;
    v_rank integer;
    v_result_id bigint;
    v_existing_id bigint;
    v_version bigint;
BEGIN
    -- Check idempotency key
    IF p_idempotency_key IS NOT NULL THEN
        SELECT id INTO v_existing_id FROM challenge_results WHERE idempotency_key = p_idempotency_key;
        IF v_existing_id IS NOT NULL THEN
            -- return existing result
            RETURN (
                SELECT jsonb_build_object(
                    'success', true,
                    'result', jsonb_build_object(
                        'id', id,
                        'playerCode', player_code,
                        'fullName', full_name,
                        'pullups', pullups,
                        'rankAtSubmission', rank_at_submission,
                        'tierName', tier_name,
                        'rewards', rewards,
                        'createdAt', created_at
                    )
                ) FROM challenge_results WHERE id = v_existing_id
            );
        END IF;
    END IF;

    -- Lock campaign_counters for sequence
    SELECT last_value INTO v_submission_no FROM campaign_counters WHERE key = 'submission_no' FOR UPDATE;
    v_submission_no := v_submission_no + 1;
    UPDATE campaign_counters SET last_value = v_submission_no, updated_at = now() WHERE key = 'submission_no';

    v_player_code := LPAD(v_submission_no::text, 6, '0');

    -- Find tier
    SELECT * INTO v_tier FROM achievement_tiers 
    WHERE p_pullups >= min_pullups AND (max_pullups IS NULL OR p_pullups <= max_pullups) AND is_active = true
    ORDER BY min_pullups DESC LIMIT 1;

    IF v_tier IS NULL THEN
        RAISE EXCEPTION 'No matching tier found for pullups %', p_pullups;
    END IF;

    -- Insert result
    INSERT INTO challenge_results (
        submission_no, player_code, full_name, pullups, tier_id, tier_name, rewards, rank_at_submission, idempotency_key
    ) VALUES (
        v_submission_no, v_player_code, p_full_name, p_pullups, v_tier.id, v_tier.title, v_tier.rewards, 0, p_idempotency_key
    ) RETURNING id INTO v_result_id;

    -- Calculate rank (including this record)
    SELECT count(*) + 1 INTO v_rank FROM challenge_results 
    WHERE is_active = true AND deleted_at IS NULL AND 
          (pullups > p_pullups OR (pullups = p_pullups AND (created_at < (SELECT created_at FROM challenge_results WHERE id = v_result_id) OR (created_at = (SELECT created_at FROM challenge_results WHERE id = v_result_id) AND id < v_result_id))));

    UPDATE challenge_results SET rank_at_submission = v_rank WHERE id = v_result_id;

    -- Refresh leaderboard if this record is in top 10
    IF v_rank <= 10 THEN
        PERFORM refresh_leaderboard_top10();
        -- Update sync version
        UPDATE leaderboard_sync SET version = version + 1, updated_at = now() WHERE id = 1 RETURNING version INTO v_version;
    END IF;

    RETURN jsonb_build_object(
        'success', true,
        'result', jsonb_build_object(
            'id', v_result_id,
            'playerCode', v_player_code,
            'fullName', p_full_name,
            'pullups', p_pullups,
            'rankAtSubmission', v_rank,
            'tierName', v_tier.title,
            'rewards', v_tier.rewards,
            'createdAt', (SELECT created_at FROM challenge_results WHERE id = v_result_id)
        )
    );
END;
$$ LANGUAGE plpgsql;

-- Trigger to refresh leaderboard when admin updates or deletes a record
CREATE OR REPLACE FUNCTION trg_refresh_leaderboard() RETURNS trigger AS $$
BEGIN
    PERFORM refresh_leaderboard_top10();
    UPDATE leaderboard_sync SET version = version + 1, updated_at = now() WHERE id = 1;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_result_change
AFTER UPDATE OR DELETE ON challenge_results
FOR EACH STATEMENT EXECUTE FUNCTION trg_refresh_leaderboard();

-- Configure RLS for challenge_results (Service role overrides this)
CREATE POLICY "Admin can do all on challenge_results" ON challenge_results TO authenticated USING (
    (auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin'))
);
